# The URL the site will be built for
base_url = "https://simulacre-simulacre.netlify.app/"

#metadata
title = "Simulacre"
description  = "元気と時間がないと言い続けて死ぬ."

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false
theme = "hyde"

# Myself
generate_feed = true
feed_filename = "rss.xml"

# Optional: enable tags
taxonomies = [
    {name = "tags"}
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
hyde_sticky = true
hyde_reverse = true
hyde_links = [
    {url = "/blog", name = "Blog"},
    {url = "/tags", name = "Tags"},
    {url = "/links", name = "Links"},
    {url = "https://twitter.com/logout", name = "How to learn everything"}
]